jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/jobs/urls.py
from django.urls import path
from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jobs import urls, views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index),
                  path('jobs/', include(urls))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jobs import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.index),
                  path('jobs/', include('jobs.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models


# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=100, unique=True, default="python")
    img = models.ImageField(upload_to='image/')
    summary = models.CharField(max_length=300)
    link = models.URLField(unique=True)

    def __str__(self):
        return self.name


class Certificate(models.Model):
    name = models.CharField(max_length=100, unique=True)
    certificate = models.ImageField(upload_to='certificates/')
    level = models.CharField(max_length=100,default="intermediate")

portfolio/jobs/models.py
from django.db import models


# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=100, unique=True, default="python")
    img = models.ImageField(upload_to='image/')
    summary = models.CharField(max_length=300)
    link = models.URLField(unique=True)

    def __str__(self):
        return self.name


class Certificate(models.Model):
    name = models.CharField(max_length=100, unique=True)
    certificate = models.ImageField(upload_to='certificates/')
    level = models.CharField(max_length=100,default="intermediate")

jobs/views.py
from django.shortcuts import render
from jobs.models import Job, Certificate


# Create your views here.
def index(request):
    jobs = Job.objects
    certificates = Certificate.objects
    return render(request, 'jobs/base.html', {'jobs': jobs, 'certificates': certificates})

# def works(request):
#     jobs = Job.objects
#     return render(request, 'jobs/works.html', {'jobs': jobs})
#
#
# def certificate(request):
#     certificates = Certificate.objects
#     return render(request, 'jobs/certificates.html', {'certificates': certificates})

portfolio/jobs/views.py
from django.shortcuts import render
from jobs.models import Job, Certificate


# Create your views here.
def index(request):
    jobs = Job.objects
    certificates = Certificate.objects
    return render(request, 'jobs/base.html', {'jobs': jobs, 'certificates': certificates})

# def works(request):
#     jobs = Job.objects
#     return render(request, 'jobs/works.html', {'jobs': jobs})
#
#
# def certificate(request):
#     certificates = Certificate.objects
#     return render(request, 'jobs/certificates.html', {'certificates': certificates})

jobs/templates/jobs/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>✖‿✖</title>

    <!-- CSS  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
<!--navbar-->
<nav class="white" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'jobs:index' %}" class="brand-logo">✖‿✖JS</a>
        <ul class="right hide-on-med-and-down">
            <li><a class="waves-effect waves-teal btn-flat " href="{% url 'jobs:index' %}">home</a></li>
            <li><a class="waves-effect waves-teal btn-flat " href="#job">works</a></li>
            <li><a class="waves-effect waves-teal btn-flat" href="#skill">skills</a></li>
            <li><a class="waves-effect waves-teal btn-flat" href="#contact">contact</a></li>
        </ul>

        <ul id="nav-mobile" class="sidenav">
            <li><a href="{% url 'jobs:index' %}">✖‿✖</a></li>
            <div class="divider"></div>
            <li><a href="#job">works</a></li>
            <div class="divider"></div>
            <li><a href="#skill">skills</a></li>
            <div class="divider"></div>
            <li><a href="#contact">contact</a></li>
            <div class="divider"></div>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>

<!--resume-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2">Jayaraj Singh</h1>
            <div class="row center">
                <h5 class="header col s12 light">A Computer Science Engineer and Developer</h5>
            </div>
            <div class="row center">
                <a href="{% static 'RESUME.docx' %}" id="download-button"
                   class="btn-large waves-effect waves-light teal lighten-1">RESUME</a>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/bck1.jpg' %}" alt="Unsplashed background img 1"></div>

</div>
<div class="section brown darken-3">

    <div class="row">
        <div class="col s12 center">
        </div>
    </div>

</div>

<!--introduction-->
<div class="container">
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
                    <h5 class="center">Introduce yourself!</h5>

                    <p class="light">Use the very first line of your “About Me” page to simply tell visitors
                        who you are. Think about how you would introduce yourself to someone who’s asked what
                        you do, and just go from there. Make sure you mention the city you’re based in.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">group</i></h2>
                    <h5 class="center">Include a photo of yourself</h5>

                    <p class="light">By utilizing elements and principles of Material Design, we were able to create
                        a
                        framework that incorporates components and animations that provide more feedback to users.
                        Additionally, a single underlying responsive system across all platforms allow for a more
                        unified user experience.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">favorite</i></h2>
                    <h5 class="center">Journals and Artworks</h5>

                    <p class="light">Are you a dog owner? Do you like to paint in your spare time?
                        Do you have a passion for skiing? It may seem unprofessional to include little details
                        like these, but a biography page that only lists work-related information about you isn’t
                        offering a complete introduction.</p>
                </div>
            </div>
        </div>

    </div>
</div>


<!--skills final-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot" id="skill">
        <div class="container">
            <br><br>
            <h4 class="white-text text-darken-4">Skills</h4><br>
            <div class="row center">
                <div class="collection ">
                    {% for cert in certificates.all %}
                        <a href="{{ cert.certificate.url }}" class="collection-item brown-text text-darken-4"><span
                                class="badge light">{{ cert.level }}</span>{{ cert.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/bck2.jpg' %}" alt="Unsplashed background img 1"></div>

</div>


<!--work section-->
<h5 class="center">My works</h5>
<div class="divider"></div>
<div class="container" id="job">
    <div class="section">
        <div class="row center">
            {% for job in jobs.all %}
                <div class="col s12 m4">
                    <div class="card card-small hoverable">
                        <div class="card-image">
                            <img src="{{ job.img.url }}" height="260">
                            <span class="card-title">{{ job.name }}</span>
                            <a href="{{ job.link }}"
                               class="btn-floating halfway-fab waves-effect waves-light teal hoverable"><i
                                    class="fab fa-github"></i></a>
                        </div>
                        <div class="card-content">
                            <p class="brown-text">{{ job.summary }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>


    </div>
</div>

<!--contact-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot" id="contact">
        <div class="container center">
            <br><br>
            <h2 class="light">Contact</h2>
            <p class="light">Address: A/46, KMDA Housing Project,Tallygunge,Kolkata-33
                <br>Phone no:+91 790043271
            </p>
            <button class="btn waves-effect white waves-teal" type="submit" name="action"><a
                    href="mailto:jayaraj.cse.97@gmail.com">
                <div class="teal-text">Email
                    <i class="material-icons teal-text right">send</i>
                </div>

            </button>


            </a>

            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/b3.jpg' %}" alt="Unsplashed background img 3"></div>

</div>


<!--footer-->
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">THANKS!</h5>
                <p class="grey-text text-lighten-4">Thank you for visiting my website ,I hope you enjoy viewing my
                    works.
                    Do check my artworks, visit again!!</p>


            </div>

            <div class="col l3 s12">
                <h5 class="white-text">My Friends</h5>
                <ul>
                    <li><a href="http://kundankumar.herokuapp.com/portfolio">
                        <div class="chip hoverable">
                            <img src="{% static 'image/kundan.jpg' %}" alt="Contact Person">
                            Kundan
                        </div>
                    </a>
                        <a class="white-text" href="http://www.avinash-info.ga/">
                            <div class="chip hoverable">
                                <img src="{% static 'image/avinash.jpg' %}" alt="Contact Person">
                                Avinash
                            </div>
                        </a>
                    </li>

                </ul>
            </div>

            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text hoverable" href="https://www.instagram.com/xix_jayraj/?hl=en"><i
                            class="fab fa-instagram"></i></a></li>
                    <li><a class="white-text hoverable" href="https://www.linkedin.com/in/jayaraj-singh-488183154/"><i
                            class="fab fa-linkedin"></i></a></li>
                    <li><a class="white-text hoverable" href="https://github.com/jayaraj19"><i
                            class="fab fa-github"></i></a></li>
                    <li><a class="white-text hoverable" href="https://www.codechef.com/users/xix_jayraj"><i
                            class="fas fa-code"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container center-align">
            Made in India <a class="brown-text text-lighten-3" href="#">© ✖‿✖ Jayaraj Singh 2018</a>
        </div>
    </div>
</footer>


<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static "js/materialize.js" %}"></script>
<script src="{% static "js/init.js" %}"></script>
</body>
</html>

portfolio/jobs/templates/jobs/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>✖‿✖</title>

    <!-- CSS  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static "css/materialize.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
<!--navbar-->
<nav class="white" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'jobs:index' %}" class="brand-logo">✖‿✖JS</a>
        <ul class="right hide-on-med-and-down">
            <li><a class="waves-effect waves-teal btn-flat " href="{% url 'jobs:index' %}">home</a></li>
            <li><a class="waves-effect waves-teal btn-flat " href="#job">works</a></li>
            <li><a class="waves-effect waves-teal btn-flat" href="#skill">skills</a></li>
            <li><a class="waves-effect waves-teal btn-flat" href="#contact">contact</a></li>
        </ul>

        <ul id="nav-mobile" class="sidenav">
            <li><a href="{% url 'jobs:index' %}">✖‿✖</a></li>
            <div class="divider"></div>
            <li><a href="#job">works</a></li>
            <div class="divider"></div>
            <li><a href="#skill">skills</a></li>
            <div class="divider"></div>
            <li><a href="#contact">contact</a></li>
            <div class="divider"></div>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>

<!--resume-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2">Jayaraj Singh</h1>
            <div class="row center">
                <h5 class="header col s12 light">A Computer Science Engineer and Developer</h5>
            </div>
            <div class="row center">
                <a href="{% static 'RESUME.docx' %}" id="download-button"
                   class="btn-large waves-effect waves-light teal lighten-1">RESUME</a>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/bck1.jpg' %}" alt="Unsplashed background img 1"></div>

</div>
<div class="section brown darken-3">

    <div class="row">
        <div class="col s12 center">
        </div>
    </div>

</div>

<!--introduction-->
<div class="container">
    <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
                    <h5 class="center">Introduce yourself!</h5>

                    <p class="light">Use the very first line of your “About Me” page to simply tell visitors
                        who you are. Think about how you would introduce yourself to someone who’s asked what
                        you do, and just go from there. Make sure you mention the city you’re based in.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">group</i></h2>
                    <h5 class="center">Include a photo of yourself</h5>

                    <p class="light">By utilizing elements and principles of Material Design, we were able to create
                        a
                        framework that incorporates components and animations that provide more feedback to users.
                        Additionally, a single underlying responsive system across all platforms allow for a more
                        unified user experience.</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
                    <h5 class="center">Proofread and edit</h5>

                    <p class="light">Are you a dog owner? Do you like to paint in your spare time?
                        Do you have a passion for skiing? It may seem unprofessional to include little details
                        like these, but a biography page that only lists work-related information about you isn’t
                        offering a complete introduction.</p>
                </div>
            </div>
        </div>

    </div>
</div>


<!--skills final-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot" id="skill">
        <div class="container">
            <br><br>
            <h4 class="white-text text-darken-4">Skills</h4><br>
            <div class="row center">
                <div class="collection ">
                    {% for cert in certificates.all %}
                        <a href="{{ cert.certificate.url }}" class="collection-item brown-text text-darken-4"><span
                                class="badge light">{{ cert.level }}</span>{{ cert.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/bck2.jpg' %}" alt="Unsplashed background img 1"></div>

</div>


<!--work section-->
<h5 class="center">My works</h5>
<div class="divider"></div>
<div class="container" id="job">
    <div class="section">
        <div class="row center">
            {% for job in jobs.all %}
                <div class="col s12 m4">
                    <div class="card card-small hoverable">
                        <div class="card-image">
                            <img src="{{ job.img.url }}" height="260">
                            <span class="card-title">{{ job.name }}</span>
                            <a href="{{ job.link }}"
                               class="btn-floating halfway-fab waves-effect waves-light teal hoverable"><i
                                    class="fab fa-github"></i></a>
                        </div>
                        <div class="card-content">
                            <p class="brown-text">{{ job.summary }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}


        </div>


    </div>
</div>

<!--contact-->
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot" id="contact">
        <div class="container center">
            <br><br>
            <h2 class="light">Contact</h2>
            <p class="light">Address: A/46, KMDA Housing Project,Tallygunge,Kolkata-33
                <br>Phone no:+91 790043271
            </p>
            <button class="btn waves-effect white waves-teal" type="submit" name="action"><a
                    href="mailto:jayaraj.cse.97@gmail.com">
                <div class="teal-text">Email
                    <i class="material-icons teal-text right">send</i>
                </div>

            </button>


            </a>

            <br><br>

        </div>
    </div>
    <div class="parallax"><img src="{% static 'image/b3.jpg' %}" alt="Unsplashed background img 3"></div>

</div>


<!--footer-->
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">THANKS!</h5>
                <p class="grey-text text-lighten-4">Thank you for visiting my website ,I hope you enjoy viewing my
                    works.
                    Do check my artworks, visit again!!</p>


            </div>

            <div class="col l3 s12">
                <h5 class="white-text">My Friends</h5>
                <ul>
                    <li><a href="http://kundankumar.herokuapp.com/portfolio">
                        <div class="chip hoverable">
                            <img src="{% static 'image/kundan.jpg' %}" alt="Contact Person">
                            Kundan
                        </div>
                    </a>
                        <a class="white-text" href="http://www.avinash-info.ga/">
                            <div class="chip hoverable">
                                <img src="{% static 'image/avinash.jpg' %}" alt="Contact Person">
                                Avinash
                            </div>
                        </a>
                    </li>

                </ul>
            </div>

            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text hoverable" href="https://www.instagram.com/xix_jayraj/?hl=en"><i
                            class="fab fa-instagram"></i></a></li>
                    <li><a class="white-text hoverable" href="https://www.linkedin.com/in/jayaraj-singh-488183154/"><i
                            class="fab fa-linkedin"></i></a></li>
                    <li><a class="white-text hoverable" href="https://github.com/jayaraj19"><i
                            class="fab fa-github"></i></a></li>
                    <li><a class="white-text hoverable" href="https://www.codechef.com/users/xix_jayraj"><i
                            class="fas fa-code"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container center-align">
            Made in India <a class="brown-text text-lighten-3" href="#">© ✖‿✖ Jayaraj Singh 2018</a>
        </div>
    </div>
</footer>


<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static "js/materialize.js" %}"></script>
<script src="{% static "js/init.js" %}"></script>
</body>
</html>